### ISSUE TITLE
glibc 2.29. Is it unavoidable dependency?

### ISSUE THREAD

**Issue by voland62** [csicar/pskt#4]
Can't use pskt on my Ubuntu 18.04 machine...

**Comment by csicar** [comment]
Should be solved in 251a1fa0d5e8391064f12cee4e9ab01da377750f . There is a link in the README

**Comment by voland62** [comment]
Thanks.

**Comment by voland62** [comment]
Have to reopen. Still getting: 
`pskt-ubuntu --version

pskt-ubuntu: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by pskt-ubuntu)`

**Comment by voland62** [comment]
Have to reopen. Still getting:
`pskt-ubuntu --version

pskt-ubuntu: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29' not found (required by pskt-ubuntu)

**Comment by csicar** [comment]
Could it be the case, that you're an older version of ubuntu?
What does `lsb_release -a` print on your system?

In case you're wondering: I build the executable for ubuntu on version `20.04`: https://github.com/csicar/pskt/blob/kotlin/.gitlab-ci.yml#L14

**Comment by voland62** [comment]
`lsb_release -a
`
`LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
`
Yes, it's older than 20.04, but it's current LTS version.
I actually compiled ncurses6(it was a quest with configure options) - I don't know, why it is not enough ncurses5 for pskt. But, it is hard to me to compile glib 2.29 - another dependency. And I still don't know if there are others..

I also tryed to build from repo(stack projects usually compile good), but got an error...

So, perhaps, new artifact for LTS version will stop this nightmare?
Thx a lot.

**Comment by csicar** [comment]
Yeah, sorry that it's so complicated. I'll also do a docker build for 18.04 :)

**Comment by csicar** [comment]
Does that work for you? https://gitlab.com/csicar/pskt/-/jobs/422305792/artifacts/browse

**Comment by csicar** [comment]
The new executable should work 18.04:
```
λ docker run -ti ubuntu:18.04  bash                                                                                                                                            
root@7de7b327c24d:/# apt update && apt install wget 
...
root@7de7b327c24d:/# wget https://gitlab.com/csicar/pskt/-/jobs/422305792/artifacts/raw/pskt-ubuntu-1804
root@7de7b327c24d:/# chmod +x pskt-ubuntu-1804
root@7de7b327c24d:/# ./pskt-ubuntu-1804 -v          
PsKt transpile:
PsKt Version: 0.1.0.0 [development build; commit: 408f66f55231882f981c03baa69e26921f7ea806 DIRTY]
done
```

**Comment by voland62** [comment]
> pskt-ubuntu-1804 -v
PsKt transpile:
PsKt Version: 0.1.0.0 [development build; commit: 408f66f55231882f981c03baa69e26921f7ea806 DIRTY]
done

Thanks for your job!
